# Common configuration to all spring config clients
---
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8010/eureka/

# Allow Eureka to recognize two apps of the same type on the same host as separate instances:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

---
spring:
  profiles: eureka-multi # Register non-Eureka server with all Eureka servers
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://eureka-secondary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
